# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.
# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:
# Input: s = "", t = "y"
# Output: "y"

def findTheDifference(s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        hashmap_s={}
        for ch in s:
            hashmap_s[ch]=hashmap_s.get(ch,0)+1
        print(hashmap_s)
        hashmap_t={}
        for ch in t:
            if hashmap_s.get(ch,0)==0:
                return ch
            hashmap_s[ch]-=1
            
            
        #     hashmap_t[ch]=hashmap_t.get(ch,0)+1
        # print(hashmap_t)
        # difference=set(hashmap_t)-set(hashmap_s)
        # print(str(difference))
        # extra=list(difference)[0]
        # return extra
        
            
        

s = "a" 
t = "aa"
print(findTheDifference(s,t))